# JWT配置
[jwt]
secret = "your-secret-key"

# 密码配置
[password]
salt = "openpick"
master_key = "openpickopenpickopenpickopenpick" #32字节
nonce = "openpickopen" # 12字节

# 待注册信息清理配置（分钟）
[pending_registration]
cleanup_minutes = 10

# 区块链配置
[blockchain]
rpc_url = "https://evmtestnet.confluxrpc.com"
token_usdt_url = "https://www.okx.com/api/v5/market/ticker?instId=CFX-USDT"
authorized_contract_address = "0x2ed3dddae5b2f321af0806181fbfa6d049be47d8"
retry_times = 5
retry_interval_seconds = 10 

# 支付设置
[payment]
rate = 5   # 5%
premium_usd = 1 # 当前 1premium 等于 1u


